#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

install_dotfiles () {
  printf "Installing Dotfiles\n"

  for dotfile in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    destination="$HOME/.$(basename "${dotfile%.*}")"

    if [ -e "$destination" ]
    then
      backup_file "$destination"
    fi

    link_file "$dotfile" "$destination"
  done
}

backup_file () {
  mv "$1" "${1}.backup"
  printf "Backed up $1 to ${1}.backup\n"
}

link_file () {
  ln -s "$1" "$2"
  printf "Linked $1 to $2\n"
}

install_dotfiles
